import 'dart:convert';
import 'dart:io';
import 'package:scores/src/data/profiles.dart';

/// Shared helpers for the golden-parity suites (the "drop the worker" port).
/// Goldens live in test/fixtures/golden/ and are generated by
/// worker/scripts/gen-goldens.mjs from the committed raw ESPN fixtures.

/// Load the registry straight off disk (no Flutter asset binding needed in tests)
/// and install it as Registry.instance so normalizers can resolve synchronously.
Registry loadTestRegistry() {
  final reg =
      Registry.fromJsonString(File('assets/league-profiles.json').readAsStringSync());
  Registry.instance = reg;
  return reg;
}

Map<String, dynamic> readGolden(String relPath) =>
    jsonDecode(File('test/fixtures/golden/$relPath').readAsStringSync())
        as Map<String, dynamic>;

dynamic readGoldenJson(String relPath) =>
    jsonDecode(File('test/fixtures/golden/$relPath').readAsStringSync());

List<dynamic> goldenIndex() =>
    jsonDecode(File('test/fixtures/golden/index.json').readAsStringSync())
        as List<dynamic>;

/// Canonical JSON: recursively sort map keys so equality is key-order-insensitive
/// and diffs are stable/readable. Lists keep their order (meaningful in our data).
String canonicalJson(dynamic v) {
  dynamic norm(dynamic x) {
    if (x is Map) {
      final keys = x.keys.map((e) => e.toString()).toList()..sort();
      return {for (final k in keys) k: norm(x[k])};
    }
    if (x is List) return x.map(norm).toList();
    // Numbers: JSON has no int/double distinction we care about here, but Dart
    // does (1 vs 1.0). Fold whole doubles to int so 20 == 20.0 across JS/Dart.
    if (x is double && x == x.roundToDouble() && x.isFinite) return x.toInt();
    return x;
  }

  return const JsonEncoder.withIndent('  ').convert(norm(v));
}
