import 'package:flutter_test/flutter_test.dart';
import 'package:scores/src/data/tournament.dart';
import 'package:scores/src/models.dart';
import 'golden_util.dart';

// Parity for the tournament layer (§2.7): the Dart normalizer in
// lib/src/data/tournament.dart must match the JS oracle (worker/src/tournament.js)
// byte-for-byte on every committed golden. Goldens are generated by
// worker/scripts/gen-goldens.mjs from REAL captured range scoreboards
// (_extra.json `tournaments`): the 2026 World Cup (groups + knockout), the full
// 2026 Wimbledon draw (seeds/sets/TBD placeholders), and the 2026 CWS
// (double-elim pools + best-of-3 championship).
void main() {
  final reg = loadTestRegistry();

  for (final e in goldenIndex().where((e) => e['endpoint'] == 'tournament')) {
    test('tournament parity: ${e['key']}', () {
      final g = readGolden(e['file'] as String);
      final a = g['args'] as Map;
      final got = normalizeTournament(reg, a['key'] as String, {
        'scoreboards': a['scoreboards'],
        if (a['standings'] != null) 'standings': a['standings'],
        if (a['grouping'] != null) 'grouping': a['grouping'],
        if (a['eventId'] != null) 'eventId': a['eventId'],
      });
      expect(canonicalJson(got), canonicalJson(g['output']));
    });

    test('tournament model parses the golden: ${e['key']}', () {
      // The tolerant models.dart parser must swallow the canonical payload whole.
      final g = readGolden(e['file'] as String);
      final t = TournamentResponse.fromJson(
          (g['output'] as Map).map((k, v) => MapEntry(k.toString(), v)));
      expect(t.league, e['key']);
      expect(t.title, isNotEmpty);
      expect(t.isEmpty, isFalse,
          reason: 'every committed tournament golden carries at least one grammar');
    });
  }
}
