import 'package:flutter_test/flutter_test.dart';
import 'package:scores/src/data/venue.dart';
import 'golden_util.dart';

// Parity for the Venue & Circuit facts tier (§2.9): the Dart normalizers in
// lib/src/data/venue.dart must match the JS oracle (worker/src/venue.js) byte-for-
// byte on every committed golden. Goldens generated by worker/scripts/gen-goldens
// from the real core venues/{id} + circuits/{id} captures in _extra.json.
void main() {
  setUpAll(loadTestRegistry);

  for (final e in goldenIndex().where((e) => e['endpoint'] == 'venue')) {
    test('venue parity: ${e['key']}/${e['venueId']}', () {
      final g = readGolden(e['file'] as String);
      final a = g['args'] as Map;
      final got = normalizeVenueFacts(a['raw']);
      expect(canonicalJson(got), canonicalJson(g['output']));
    });
  }

  for (final e in goldenIndex().where((e) => e['endpoint'] == 'circuit')) {
    test('circuit parity: ${e['key']}/${e['circuitId']}', () {
      final g = readGolden(e['file'] as String);
      final a = g['args'] as Map;
      final got = normalizeCircuitFacts(a['raw'], a['driver']);
      expect(canonicalJson(got), canonicalJson(g['output']));
    });
  }
}
