import 'package:flutter_test/flutter_test.dart';
import 'package:scores/src/data/athlete.dart';
import 'golden_util.dart';

// Parity for the athlete/player profile tier (§2.6 "Player rows"): the Dart
// normalizer in lib/src/data/athlete.dart must match the JS oracle
// (worker/src/athlete.js) byte-for-byte on every committed golden. Goldens are
// generated by worker/scripts/gen-goldens from the real core athletes/{id} +
// statistics + eventlog captures in _extra.json (identity/team/statistics/games
// all pre-resolved, exactly as api.dart assembles them at runtime).
void main() {
  setUpAll(loadTestRegistry);

  for (final e in goldenIndex().where((e) => e['endpoint'] == 'athlete')) {
    test('athlete parity: ${e['key']}/${e['athleteId']}', () {
      final g = readGolden(e['file'] as String);
      final a = g['args'] as Map;
      final got = normalizeAthleteProfile(a['key'] as String, a['athleteId'].toString(), {
        'identity': a['identity'],
        'team': a['team'],
        'statistics': a['statistics'],
        'games': a['games'],
      });
      expect(canonicalJson(got), canonicalJson(g['output']));
    });
  }
}
